version: '3.9'
services:
  my-sql: 
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest-tur
      MYSQL_USER: neel
      MYSQL_PASSWORD: neel
    volumes:
      - ./data/mysql:/var/lib/mysql

# run : docker-compose up -d
